# Generated by Django 4.2.3 on 2023-07-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
