# Generated by Django 4.2.2 on 2023-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteuser',
            name='address',
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
