# Generated by Django 4.2.3 on 2023-07-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_book_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=1.11, max_digits=2),
        ),
    ]
