# Generated by Django 4.2.2 on 2023-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0003_websiteuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Credit Card Number'),
        ),
    ]
