# Generated by Django 4.2.3 on 2023-07-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0003_alter_book_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.ManyToManyField(related_name='books', to='bookstore_app.rating'),
        ),
    ]
