# Generated by Django 4.2.3 on 2023-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0005_remove_book_ratings_alter_rating_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookRating',
            field=models.FloatField(default=0.0),
        ),
    ]
