# Generated by Django 4.2.3 on 2023-07-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0006_book_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
