# Generated by Django 4.2.3 on 2023-07-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0007_publisher_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
